# Generated by Django 4.2.23 on 2025-06-24 21:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("logbook", "0002_remove_logbookentry_logbook_entry_date_not_future_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logbookentry",
            options={
                "ordering": ["-date", "-updated_at"],
                "verbose_name": "Logbook Entry",
                "verbose_name_plural": "Logbook Entries",
            },
        ),
        migrations.RemoveConstraint(
            model_name="logbookentry",
            name="logbook_entry_valid_age",
        ),
        migrations.AddField(
            model_name="logbookentry",
            name="location_of_activity",
            field=models.CharField(
                default="", help_text="Location of clinical activity", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="logbookentry",
            name="management_action",
            field=models.TextField(
                default="", help_text="Management action (narrative text)"
            ),
        ),
        migrations.AddField(
            model_name="logbookentry",
            name="submitted_to_supervisor_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when entry was formally submitted to supervisor",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="logbookentry",
            name="supervisor_action_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when supervisor last took action",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="logbookentry",
            name="topic_subtopic",
            field=models.CharField(
                default="",
                help_text="Topic/Subtopic (free text for now)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="case_title",
            field=models.CharField(
                help_text="Title of case or diagnosis", max_length=300
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="clinical_reasoning",
            field=models.TextField(
                blank=True, help_text="Clinical reasoning and thought process"
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp when the entry was first created",
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this entry (should be the PG)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_logbook_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="date",
            field=models.DateField(help_text="Date of case"),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="learning_points",
            field=models.TextField(
                blank=True, help_text="Key learning points from this case"
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="patient_age",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Patient age in years",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="patient_chief_complaint",
            field=models.TextField(
                blank=True, help_text="Patient's chief complaint or presenting symptoms"
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="patient_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                    ("U", "Unknown/Not Specified"),
                ],
                help_text="Patient gender",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="patient_history_summary",
            field=models.TextField(
                default="", help_text="Brief history (narrative text)"
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="primary_diagnosis",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary diagnosis",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_entries",
                to="logbook.diagnosis",
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Supervisor Review"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned for Edits"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Current status of the entry",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned supervising consultant",
                limit_choices_to={"role__in": ["supervisor", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="supervisor_feedback",
            field=models.TextField(
                blank=True,
                help_text="Supervisor's comment or reason for rejection/return.",
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of the last modification"
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when entry was approved by supervisor",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor who approved this entry",
                limit_choices_to={"role__in": ["supervisor", "admin"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_logbook_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="logbookentry",
            index=models.Index(
                fields=["submitted_to_supervisor_at"],
                name="logbook_log_submitt_0823dd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="logbookentry",
            index=models.Index(
                fields=["supervisor_action_at"], name="logbook_log_supervi_097359_idx"
            ),
        ),
    ]
