# Generated by Django 4.2.23 on 2025-06-25 05:22

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0003_alter_logbookentry_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="logbookentry",
            name="logbook_entry_date_not_future",
        ),
        migrations.AddConstraint(
            model_name="logbookentry",
            constraint=models.CheckConstraint(
                check=models.Q(("date__lte", datetime.date(2025, 6, 25))),
                name="logbook_entry_date_not_future",
            ),
        ),
    ]
