# Generated by Django 4.2.25 on 2025-10-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("logbook", "0005_historicallogbookreview_historicalprocedure_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="logbookentry",
            name="logbook_entry_date_not_future",
        ),
    ]
