# Generated by Django 4.2.25 on 2025-10-15 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_historicalcasecategory_historicalclinicalcase_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clinicalcase',
            name='case_date_not_future',
        ),
    ]
