[tool.black]
line-length = 100
target-version = ['py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
    \.git
  | \.venv
  | venv
  | env
  | \.mypy_cache
  | \.pytest_cache
  | \.tox
  | build
  | dist
  | migrations
  | staticfiles
)/
'''

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "sims_project.settings"
python_files = ["tests.py", "test_*.py", "*_test.py"]
python_classes = ["Test*", "*Tests", "*TestCase"]
python_functions = ["test_*"]
testpaths = ["sims", "tests"]
addopts = [
    "--reuse-db",
    "--nomigrations",
    "--cov=sims",
    "--cov-report=html",
    "--cov-report=term-missing:skip-covered",
    "--cov-fail-under=80",
    "-v",
]

[tool.coverage.run]
source = ["sims"]
omit = [
    "*/migrations/*",
    "*/tests/*",
    "*/test_*.py",
    "*/__pycache__/*",
    "*/venv/*",
    "*/env/*",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "def __str__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
]
precision = 2
