# Generated by Django 4.2.25 on 2025-10-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0006_remove_date_constraint'),
        ('cases', '0003_remove_date_constraint'),
        ('certificates', '0002_historicalcertificatetype_historicalcertificate'),
        ('rotations', '0002_historicalrotation_historicalhospital_and_more'),
    ]

    operations = [
        # Add indexes for frequently queried fields
        migrations.RunSQL(
            sql=[
                # Logbook indexes for analytics queries
                "CREATE INDEX IF NOT EXISTS idx_logbook_pg_date ON logbook_logbookentry(pg_id, date);",
                "CREATE INDEX IF NOT EXISTS idx_logbook_supervisor_date ON logbook_logbookentry(supervisor_id, date);",
                "CREATE INDEX IF NOT EXISTS idx_logbook_status_date ON logbook_logbookentry(status, date);",
                
                # Case indexes for analytics queries
                "CREATE INDEX IF NOT EXISTS idx_case_pg_date ON cases_clinicalcase(pg_id, date_encountered);",
                "CREATE INDEX IF NOT EXISTS idx_case_category ON cases_clinicalcase(category_id, date_encountered);",
                
                # Certificate indexes
                "CREATE INDEX IF NOT EXISTS idx_cert_pg_status ON certificates_certificate(pg_id, status);",
                "CREATE INDEX IF NOT EXISTS idx_cert_issue_date ON certificates_certificate(issue_date);",
                
                # Rotation indexes
                "CREATE INDEX IF NOT EXISTS idx_rotation_pg_dates ON rotations_rotation(pg_id, start_date, end_date);",
                "CREATE INDEX IF NOT EXISTS idx_rotation_supervisor ON rotations_rotation(supervisor_id, status);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_logbook_pg_date;",
                "DROP INDEX IF EXISTS idx_logbook_supervisor_date;",
                "DROP INDEX IF EXISTS idx_logbook_status_date;",
                "DROP INDEX IF EXISTS idx_case_pg_date;",
                "DROP INDEX IF EXISTS idx_case_category;",
                "DROP INDEX IF EXISTS idx_cert_pg_status;",
                "DROP INDEX IF EXISTS idx_cert_issue_date;",
                "DROP INDEX IF EXISTS idx_rotation_pg_dates;",
                "DROP INDEX IF EXISTS idx_rotation_supervisor;",
            ],
        ),
    ]
