# Generated by Django 4.2.25 on 2025-10-10 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRotation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Start date of the rotation"),
                ),
                ("end_date", models.DateField(help_text="End date of the rotation")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("ongoing", "Ongoing"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("pending", "Pending Approval"),
                        ],
                        default="planned",
                        help_text="Current status of the rotation",
                        max_length=20,
                    ),
                ),
                (
                    "objectives",
                    models.TextField(
                        blank=True,
                        help_text="Specific learning objectives for this rotation",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.TextField(
                        blank=True,
                        help_text="Expected learning outcomes and competencies",
                    ),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text="Requirements and prerequisites for this rotation",
                    ),
                ),
                (
                    "completion_certificate",
                    models.TextField(
                        blank=True,
                        help_text="Completion certificate for the rotation",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "feedback",
                    models.TextField(
                        blank=True,
                        help_text="Overall feedback and comments on the rotation",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes and observations"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when rotation was approved",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who approved this rotation",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this rotation assignment",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Department where rotation takes place",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rotations.department",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Hospital where rotation takes place",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rotations.hospital",
                    ),
                ),
                (
                    "pg",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Postgraduate assigned to this rotation",
                        limit_choices_to={"role": "pg"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Supervisor assigned to oversee this rotation",
                        limit_choices_to={"role": "supervisor"},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rotation",
                "verbose_name_plural": "historical Rotations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHospital",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Official name of the hospital", max_length=200
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hospital code or abbreviation",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, help_text="Complete hospital address"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Hospital contact phone number",
                        max_length=20,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Hospital contact email", max_length=254
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Hospital website URL"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of hospital and its specialties",
                    ),
                ),
                (
                    "facilities",
                    models.TextField(
                        blank=True, help_text="Available facilities and equipment"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this hospital is currently accepting rotations",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Hospital",
                "verbose_name_plural": "historical Hospitals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDepartment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the department", max_length=200
                    ),
                ),
                (
                    "head_of_department",
                    models.CharField(
                        blank=True,
                        help_text="Name of the department head",
                        max_length=200,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, help_text="Department contact email", max_length=254
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, help_text="Department contact phone", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of the department and its services",
                    ),
                ),
                (
                    "training_objectives",
                    models.TextField(
                        blank=True,
                        help_text="Learning objectives for rotations in this department",
                    ),
                ),
                (
                    "required_skills",
                    models.TextField(
                        blank=True,
                        help_text="Skills that should be acquired during rotation",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this department is currently accepting rotations",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Hospital this department belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="rotations.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Department",
                "verbose_name_plural": "historical Departments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
