name: Django Test Suite

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: django-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint and test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    env:
      DJANGO_SETTINGS_MODULE: sims_project.settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest pytest-django beautifulsoup4

      - name: Prepare Django environment
        run: |
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run pytest
        run: pytest --ds=sims_project.settings --maxfail=1 --disable-warnings -q
        continue-on-error: true

      - name: Upload pytest artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-failures
          path: .pytest_cache
          if-no-files-found: ignore
